name: worktrackr
description: Multi-factor employee attendance system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation + deep links
  go_router: ^14.2.0
  app_links: ^6.3.2

  # Networking
  dio: ^5.4.3+1

  # Secure storage (JWT)
  flutter_secure_storage: ^9.2.2

  # Biometric auth
  local_auth: ^3.0.1

  # GPS
  geolocator: ^12.0.0

  # Wi-Fi / connectivity
  connectivity_plus: ^7.1.1

  # Device ID
  device_info_plus: ^12.4.0

  # Offline queue
  hive_flutter: ^1.1.0

  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar_v2: ^6.3.2
  geocoding: ^4.0.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  safe_device: ^1.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
